MAJ vocab Appendix v2 01/2022
sallesma/timeout-ultimate pull request #14
Opened 2022-02-22 12:48 UTC by hippalectryon-0

2022-02-23 21:59 UTC, sallesma requested changes

2022-02-23 21:59 UTC, sallesma commented on data/rules/handSignals.js
> +    name: 'Personnel ratio hommes',
J'ai peur qu'on y perde les francophones (seuls utilisateurs de l'appli).

Finalement, une traduction française serait sans doute la bienvenue ? (traduction maison car la ffdf est en retard là dessus)

Ratio : hommes / Ratio : femmes ferait l'affaire ?

2022-02-23 23:16 UTC, hippalectryon-0 commented on data/rules/handSignals.js
> +    name: 'Personnel ratio hommes',
_Ratio : hommes / Ratio : femmes_ me semble bien :)

2022-03-01 10:14 UTC, sallesma approved these changes

2022-03-01 10:14 UTC, merged

2022-03-01 10:15 UTC, sallesma commented
Merci ;)